apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - image: sandysinghitechno/poc_backstage_cicd-product-service:v1.0
        name: demo-api
        ports:
        - containerPort: 4001
